# Generated by Django 5.2.17 on 2026-09-29 17:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoryComic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bab', models.PositiveIntegerField(unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('unlock_level', models.PositiveIntegerField(default=1)),
                ('total_pages', models.PositiveIntegerField(default=1)),
            ],
            options={
                'ordering': ['bab'],
            },
        ),
    ]
